apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: currency-service-allow-egress
spec:
  podSelector:
    matchLabels:
      app: currencyservice
  policyTypes:
    - Egress
  egress: []